--- #YAML:1.0
name:               GTM
version:            0.6
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:             5.24
    common::sense:        3
    File::HomeDir:        0.89
    Gtk2:                 1.043
    Gtk2::Ex::PodViewer:  0.18
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
